name: CI

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Send pull request number to endpoint
      run: |
        curl -X POST -H "Content-Type: application/json" -d '{"pull_request_number": ${{ github.event.pull_request.number }}}' https://e5be-23-112-11-217.ngrok-free.app/review_build_error_logs
